// <auto-generated />
using System;
using CEMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEMS.Data.Migrations
{
    [DbContext(typeof(CEMSDbContext))]
    partial class CEMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CEMS.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Description = "Hands-on intro to machine learning basics.",
                            Name = "AI Fundamentals",
                            Type = "Workshop"
                        },
                        new
                        {
                            ActivityId = 2,
                            Description = "Industry alumni share hiring and portfolio tips.",
                            Name = "Career Talk",
                            Type = "Talk"
                        },
                        new
                        {
                            ActivityId = 3,
                            Description = "Team-based programming challenge with prizes.",
                            Name = "Coding Challenge",
                            Type = "Game"
                        });
                });

            modelBuilder.Entity("CEMS.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Events_Capacity", "Capacity > 0");
                        });

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Capacity = 180,
                            Description = "University-wide community event with talks and workshops.",
                            EventDate = new DateTime(2026, 9, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tech Connect 2026"
                        },
                        new
                        {
                            EventId = 2,
                            Capacity = 50,
                            Description = "A collaborative coding sprint for students and local mentors.",
                            EventDate = new DateTime(2026, 10, 5, 9, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Code Sprint Weekend"
                        });
                });

            modelBuilder.Entity("CEMS.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Role").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CEMS.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            EventId = 1,
                            ParticipantId = 1,
                            RegistrationDate = new DateTime(2026, 7, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            RegistrationId = 2,
                            EventId = 1,
                            ParticipantId = 2,
                            RegistrationDate = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("CEMS.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("VenueId");

                    b.ToTable("Venues", t =>
                        {
                            t.HasCheckConstraint("CK_Venues_Capacity", "Capacity > 0");
                        });

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "Block A, Main Campus",
                            Capacity = 200,
                            Name = "Innovation Hall"
                        },
                        new
                        {
                            VenueId = 2,
                            Address = "Block C, Room 301",
                            Capacity = 60,
                            Name = "Computer Lab 3"
                        },
                        new
                        {
                            VenueId = 3,
                            Address = "North Field",
                            Capacity = 500,
                            Name = "Open Ground"
                        });
                });

            modelBuilder.Entity("EventActivity", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("EventActivities", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            ActivityId = 1
                        },
                        new
                        {
                            EventId = 1,
                            ActivityId = 2
                        },
                        new
                        {
                            EventId = 2,
                            ActivityId = 3
                        });
                });

            modelBuilder.Entity("EventVenue", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("EventVenues", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("CEMS.Models.Administrator", b =>
                {
                    b.HasBaseType("CEMS.Models.Person");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            PersonId = 100,
                            Email = "admin@uni.edu",
                            Name = "Admin User",
                            Phone = "555-0000",
                            Permissions = ""
                        });
                });

            modelBuilder.Entity("CEMS.Models.Participant", b =>
                {
                    b.HasBaseType("CEMS.Models.Person");

                    b.HasDiscriminator().HasValue("Participant");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Email = "anita.sharma@uni.edu",
                            Name = "Anita Sharma",
                            Phone = "555-0101"
                        },
                        new
                        {
                            PersonId = 2,
                            Email = "rahul.karki@uni.edu",
                            Name = "Rahul Karki",
                            Phone = "555-0102"
                        },
                        new
                        {
                            PersonId = 3,
                            Email = "mina.gurung@uni.edu",
                            Name = "Mina Gurung",
                            Phone = "555-0103"
                        });
                });

            modelBuilder.Entity("CEMS.Models.Registration", b =>
                {
                    b.HasOne("CEMS.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CEMS.Models.Participant", "Participant")
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("EventActivity", b =>
                {
                    b.HasOne("CEMS.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CEMS.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventVenue", b =>
                {
                    b.HasOne("CEMS.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CEMS.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CEMS.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("CEMS.Models.Participant", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
